@startuml
skinparam linetype Ortho
class Puml2HtmlDocGenerator {
    int MAX_THREADS
    org.slf4j.Logger logger
    private void createDirectoryIfNotExists(String directoryPath)
    private String extractDescription(String pumlContent, String defaultDescription)
    private String extractTitle(String pumlContent, String defaultTitle)
    private List<File> findPumlFiles(String directoryPath)
    public void generateHtmlDocumentation(String docTitle, HtmlGenerationContext context, ProgressTracker progressTracker)
    private DiagramResult processFile(File inputFile, String outputDir, ProgressTracker progressTracker)
    private Map<String,DiagramInfo> processFilesAndGenerateDocs(List<File> files, String outputDir, String diagTemplate, ProgressTracker progressTracker)
}
Puml2HtmlDocGenerator --> HtmlGenerationContext : caller-callee
Puml2HtmlDocGenerator --> HtmlGenerator : caller-callee
Puml2HtmlDocGenerator --> ProgressTracker : caller-callee
Puml2HtmlDocGenerator --> DiagramResult : caller-callee
Puml2HtmlDocGenerator -- WorkUnitType : association
Puml2HtmlDocGenerator --> PathResolver : caller-callee
Puml2HtmlDocGenerator -- DirectoryConstants : association
@enduml
