@startuml
skinparam linetype Ortho
class JavaDocClassPageGenerator {
    org.slf4j.Logger logger
    public void generateClassPage(CodeEntity codeEntity, JavaDocGenerationContext context)
    private Map<String,String> preparePlaceholders(CodeEntity codeEntity)
}
JavaDocClassPageGenerator --> JavaDocGenerationContext : caller-callee
JavaDocClassPageGenerator --> JavaDocHtmlGenerator : caller-callee
JavaDocClassPageGenerator --> JavaDocGenerationContext : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> JavaDocHtmlGenerator : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> MethodEntity : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> FieldEntity : caller-callee
JavaDocClassPageGenerator --> FieldEntity : caller-callee
JavaDocClassPageGenerator --> FieldEntity : caller-callee
JavaDocClassPageGenerator --> FieldEntity : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> Relative : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> Relative : caller-callee
JavaDocClassPageGenerator --> Relative : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
JavaDocClassPageGenerator --> CodeEntity : caller-callee
@enduml
