@startuml
skinparam linetype Ortho
class Scenario {
    String entryClass
    List<Interaction> interactions
    org.slf4j.Logger logger
    String startingMethod
    public void addInteraction(Interaction interaction)
    public String getEntryClass()
    public List<Interaction> getInteractions()
    public String getStartingMethod()
    public String toPlantUmlSyntax()
}
Scenario --> Interaction : caller-callee
@enduml
