@startuml
skinparam linetype Ortho
class DefaultContextFactory {
    Properties properties
    public GUIStyleContext createGUIStyleContext()
    public HtmlGenerationContext createHTMLContext()
    public JavaDocGenerationContext createJavaDocContext()
    public UMLGenerationContext createUMLContext()
    public UMLGenerationContext getContextFromFile(String propertiesFile)
}
DefaultContextFactory --> PathResolver : caller-callee
DefaultContextFactory -- DirectoryConstants : association
DefaultContextFactory -- ResourcePaths : association
DefaultContextFactory --> GUIStylePathResolver : caller-callee
DefaultContextFactory -- StyleConstants : association
DefaultContextFactory --> ConfigurationLoader : caller-callee
@enduml
