@startuml
skinparam linetype Ortho
class JavaDocGenerator {
    org.slf4j.Logger logger
    private void copyCssToOutputDirectory(JavaDocGenerationContext context)
    private void generateClassDocumentation(Map<String,PackageEntity> packageEntities, JavaDocGenerationContext context, ProgressTracker progressTracker)
    private void generateIndexDocumentation(Map<String,PackageEntity> packageEntities, JavaDocGenerationContext context)
    public void generateJavaDoc(JavaDocGenerationContext context, ProgressTracker progressTracker)
    private void generatePackageDocumentation(Map<String,PackageEntity> packageEntities, JavaDocGenerationContext context, ProgressTracker progressTracker)
}
JavaDocGenerator --> ProgressTracker : caller-callee
JavaDocGenerator --> ProjectAnalyzer : caller-callee
JavaDocGenerator -- WorkUnitType : association
JavaDocGenerator --> PackageDiagramService : caller-callee
JavaDocGenerator --> JavaDocPackagePageGenerator : caller-callee
JavaDocGenerator --> PackageEntity : caller-callee
JavaDocGenerator --> ClassDiagramService : caller-callee
JavaDocGenerator --> JavaDocClassPageGenerator : caller-callee
JavaDocGenerator --> JavaDocIndexPageGenerator : caller-callee
JavaDocGenerator --> JavaDocGenerationContext : caller-callee
@enduml
