@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.PreviewTab::handleBrowse
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : handleBrowse calls resetImageView
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : handleBrowse calls displayImage
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : handleBrowse calls updateNavigationButtons
@enduml