@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.PreviewTab::loadOutputDirectory
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.uml.util.UMLGenerationContext : loadOutputDirectory calls getOutputDirectory
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : loadOutputDirectory calls resetImageView
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : loadOutputDirectory calls displayImage
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : loadOutputDirectory calls updateNavigationButtons
@enduml