@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.UmlGenTab::createConfigurationOptionsBox
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.gui.UmlGenTab : createConfigurationOptionsBox calls updateCustomInputsVisibility
@enduml