@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.UmlGenTab::createCustomInputsPane
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.gui.UmlGenTab : createCustomInputsPane calls createDirectoryButton
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.gui.UmlGenTab : createCustomInputsPane calls createDirectoryButton
@enduml