@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.UmlGenTab::selectDefaultTheme
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.gui.util.GUIStyleContext : selectDefaultTheme calls getDefaultStylePath
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.gui.util.GUIStyleContext : selectDefaultTheme calls getDarkThemePath
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.gui.util.GUIStyleContext : selectDefaultTheme calls getLightThemePath
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.gui.util.GUIStyleContext : selectDefaultTheme calls getPastelThemePath
@enduml