@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.JavaDocGenTab::addInputDirectorySection
com.pjsoft.j2arch.gui.JavaDocGenTab -> com.pjsoft.j2arch.docgen.javadoc.util.JavaDocGenerationContext : addInputDirectorySection calls getInputDirectory
@enduml