@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.PreviewTab::handleRightNavigation
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : handleRightNavigation calls resetImageView
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : handleRightNavigation calls displayImage
com.pjsoft.j2arch.gui.PreviewTab -> com.pjsoft.j2arch.gui.PreviewTab : handleRightNavigation calls updateNavigationButtons
@enduml