@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.UmlGenTab::getContextFromFile
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.config.ConfigurationLoader : getContextFromFile calls loadProperties
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.config.DefaultContextFactory : getContextFromFile calls createUMLContext
@enduml