@startuml
title Sequence Diagram for com.pjsoft.j2arch.gui.UmlGenTab::createGenerateButton
com.pjsoft.j2arch.gui.UmlGenTab -> com.pjsoft.j2arch.gui.UmlGenTab : createGenerateButton calls handleGenerateAction
@enduml